const REGISTER_USER = "REGISTER_USER"
const VERIFY_USER = "VERIFY_USER"
const FETCH_USERS = "FETCH_USERS"
const SEND_MESSAGE = "SEND_MESSAGE"
const GET_CHAT_BY_ID = "GET_CHAT_BY_ID"

module.exports = {
  REGISTER_USER,
  VERIFY_USER,
  FETCH_USERS,
  SEND_MESSAGE,
  GET_CHAT_BY_ID
}